config/routes.rb
Rails.application.routes.draw do
 

  resources :transactions
  resources :items
  resources :models
  get 'home/index'

  devise_for :users

  root 'home#index'
  get '/about', to: 'static_pages#about'
  get '/index', to: 'home#index'
  get '/item', to: 'items#browseAll'
  get '/user', to: 'users#index'
  get '/account', to: 'users#account'
  get '/post_item', to: 'items#new'
  get '/browse_all', to: 'items#index'
  get '/item_details', to: 'items#show'
  get '/destroy_items', to: 'items#destroy'
  get '/manage_items', to: 'items#manage'
  get '/view_cart', to: 'carts#index'
  get '/add_to_cart', to: 'carts#create'
  get '/clear_cart', to: 'carts#clear'
  get '/cart_details', to: 'carts#show'
  get '/check_out', to: 'transactions#updateTransaction'
  get '/transaction_record', to: 'transactions#create'
  get '/view_transactions', to: 'transactions#index'
  get '/list',to:'books#index'
  get '/search', to: 'home#search'
  get '/invalidManage', to: 'items#invalidManage'
  resource :users
  resource :items
  resource :carts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :items, dependent: :destroy
  has_many :carts, dependent: :destroy
  has_many :transactions, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, uniqueness: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def account
	end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: current_user.email, class: "gravatar")
  end
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<!--

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :item_name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :item_price %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category, id: :item_category %>
  </div>

  <div class="field">
    <%= form.label :condition %>
    <%= form.text_field :condition, id: :item_condition %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :item_description %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :item_user_id %>
  </div>
-->

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/account.html.erb
<!DOCTYPE html>
<html>
  <body class="profile">
    <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <h1 id="title1">
            <%= image_tag("account.png", alt: "logo", id: "account") %>
            The personal account page
        </h1>
        <h2 id="title2">
            Welcome, <%= current_user.email %>! <br /> <br />
            <%= link_to "Log Out".html_safe, destroy_user_session_path, :method => :delete %>
        </h2>
    </div>
    </header>
    <div class="card">
        <div class="img">
            <%= gravatar_for current_user %>
        </div>
        <h3>Hi,</h3>
        <p class="title"><%= current_user.email %>!</p>
        <p> Your current balance is: <br />$ 1,000</p>
    </div>
        <div id="table1">
            <li class="row">
                <div class="col column1">Change your password:</div>
                <div class="col column2"><%= link_to 'Edit', edit_user_registration_path %></div>
            </li>
            <li class="row">
                <div class="col column1">Manage your posted items:</div>
                <div class="column2"><%= link_to 'Posted items', manage_items_path %></div>
            </li>
            <li class="row">
                <div class="col column1">Your parchase history:</div>
                <div class="col column2"><%= link_to 'Parchased items', view_transactions_path %></div>
            </li>
        </div>
        <%= render 'layouts/footer' %>
    </body>
</html>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', item: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
<!--
      <th>Price</th>
      <th>Category</th>
      <th>Condition</th>
      <th>Description</th>
      <th>User</th>
-->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
<!--
        <td><%= item.price %></td>
        <td><%= item.category %></td>
        <td><%= item.condition %></td>
        <td><%= item.description %></td>
        <td><%= item.user %></td>
-->
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>