config/routes.rb
Rails.application.routes.draw do
 

  resources :transactions
  resources :items
  resources :models
  get 'home/index'

  devise_for :users

  root 'home#index'
  get '/about', to: 'static_pages#about'
  get '/index', to: 'home#index'
  get '/item', to: 'items#browseAll'
  get '/user', to: 'users#index'
  get '/account', to: 'users#account'
  get '/post_item', to: 'items#new'
  get '/browse_all', to: 'items#index'
  get '/item_details', to: 'items#show'
  get '/destroy_items', to: 'items#destroy'
  get '/manage_items', to: 'items#manage'
  get '/view_cart', to: 'carts#index'
  get '/add_to_cart', to: 'carts#create'
  get '/clear_cart', to: 'carts#clear'
  get '/cart_details', to: 'carts#show'
  get '/check_out', to: 'transactions#updateTransaction'
  get '/transaction_record', to: 'transactions#create'
  get '/view_transactions', to: 'transactions#index'
  get '/list',to:'books#index'
  get '/search', to: 'home#search'
  get '/invalidManage', to: 'items#invalidManage'
  resource :users
  resource :items
  resource :carts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def search
    @search_string = params[:search_string]
    @item_list = Item.ransack(name_cont: @search_string)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="mainpage">
<% if user_signed_in? %> <!-- Provided by devise -->
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
	<div class="container-fluid"> 
    <div class="navbar-nav">
      <%= link_to "Account".html_safe, account_path %>
      <%= link_to "Sell".html_safe, new_item_path %> 
      <%= link_to "Browse All".html_safe,  browse_all_path %> 
      <%= link_to "My Cart".html_safe,  view_cart_path %>
      <%= link_to "My Sells ".html_safe,  manage_items_path %>
      <%= link_to "Order".html_safe,  view_transactions_path %>
      <%= link_to "Log Out ".html_safe, destroy_user_session_path, :method => :delete %>
      <%= link_to 'About', about_path %>
    </div>
	</div>
</nav>
    <% end %>
    <% unless user_signed_in? %>
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
	<div class="container-fluid"> 
    <div class="navbar-nav">
        <%= link_to 'Sign up', new_user_registration_path %> 
        <%= link_to 'Log in', new_user_session_path %>
    </div>
	</div>
</nav>
<% end %>
</div>
<div>
<h1 class="title">Buckeye Exchange</h1>
<div class="search_bar">
  <form action="search" method="get">
    <input type="text" name="search_string" id="search">
    <button type="submit" value="find">  GO!</button>
  </form>
</div>
</div>

app/views/home/search.html.erb
<head>
<div>
<h1 class="title">Buckeye Exchange</h1>
</div>
<div class="search_bar">
  <form action="search" method="get">
    <input type="text" name="search_string" id="search" value=<%= @search_string %>>
	<button type="submit" value="find">GO!</button>
  </form>
</div>
</head>

<ul class="products">
  <% @item_list.result.each do |item| %>
    <% if item.availability == 'available' %>
    <li class="product design">
    <div>
        <%= image_tag item.picture if item.picture? %>
        <h5><%= link_to item[:name], item %></h5>
        <span class="price"><%= item[:price] %></span>      
    </div>
    <% if user_signed_in? %>
    <div class="addto-cart">
     <%= link_to "Add to cart", {:controller => "carts", :action => "create", :name => item.name, :price => item.price, :category => item.category, :condition => item.condition, :description => item.description, :picture => item.picture, :item => item }%>
    </div>
    <% end %>
    </li>
    <% end %>
  <% end %>
</ul>
<%= render 'layouts/footer' %>