config/routes.rb
Rails.application.routes.draw do
 

  resources :transactions
  resources :items
  resources :models
  get 'home/index'

  devise_for :users

  root 'home#index'
  get '/about', to: 'static_pages#about'
  get '/index', to: 'home#index'
  get '/item', to: 'items#browseAll'
  get '/user', to: 'users#index'
  get '/account', to: 'users#account'
  get '/post_item', to: 'items#new'
  get '/browse_all', to: 'items#index'
  get '/item_details', to: 'items#show'
  get '/destroy_items', to: 'items#destroy'
  get '/manage_items', to: 'items#manage'
  get '/view_cart', to: 'carts#index'
  get '/add_to_cart', to: 'carts#create'
  get '/clear_cart', to: 'carts#clear'
  get '/cart_details', to: 'carts#show'
  get '/check_out', to: 'transactions#updateTransaction'
  get '/transaction_record', to: 'transactions#create'
  get '/view_transactions', to: 'transactions#index'
  get '/list',to:'books#index'
  get '/search', to: 'home#search'
  get '/invalidManage', to: 'items#invalidManage'
  resource :users
  resource :items
  resource :carts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = current_user.carts
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    @cart = Cart.find(params[:id])
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    exist = false
    current_user.carts.each do |c|
      if c.item == cart_params.fetch("item")
       exist = true
       break
      end
    end
    if !exist 
      @cart = current_user.carts.new(cart_params)
    else
      @cart = User.new.carts.new
    end
      if @cart.save
        redirect_to view_cart_path
      else
        redirect_to view_cart_path
      end
  end

  def del
    current_user.carts.destroy_all
    render :index
  end
  
  def clear
    current_user.carts.destroy_all
    render :index
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  def addToCart
    @item = Item.find(params[:item])
    @cart = Cart.new
    @cart.user = current_user
    @cart.name = "Scooter"
    @carts = Cart.all
    render :index
  end

  def emptyCart
  end

  def display
    @carts = current_user.carts
    if @carts.any?
      render :index
    else
      render :emptyCart
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.permit(:name, :price, :category, :condition, :description, :picture, :item)
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/del.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<% if current_user.carts.any? %>

	<table>
	  <thead>
	    <tr>
	      <th>Name</th>
	      <th>Price</th>
	      <th>Category</th>
	      <th>Condition</th>
	      <th>Description</th>
	      <th>Picture</th>
	<!--
	      <th>User</th>
	-->
	      <th colspan="3"></th>
	    </tr>
	  </thead>

	  <tbody>
	    <% @carts.each do |cart| %>
	      <tr>
		<td><%= cart.name %></td>
		<td><%= cart.price %></td>
		<td><%= cart.category %></td>
		<td><%= cart.condition %></td>
		<td><%= cart.description %></td>
		<td><%= cart.picture.url %></td>
		<td><%= link_to 'Delete', delete_cart_path %></td>
	<!--
		<td><%= image_tag cart.picture.url if cart.picture? %></td>
		<td><%= cart.user %></td>
	-->
	      </tr>
	    <% end %>
	  </tbody>
	</table>

	<br>

	<%= link_to 'Remove all', clear_cart_path %>

	<%= link_to 'Check Out', check_out_path %>

<% end %>

<%= link_to 'Post a new item on sale!', new_item_path %>
<%= link_to 'Back to homepage', root_path %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/emptyCart.erb
<p id="notice"><%= notice %></p>

<h1>Cart</h1>

<h2>You haven't put any item in cart.</h2>

<br>

<%= link_to 'Browse all!', browse_all_path %>
<br>
<%= render 'layouts/footer' %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>
  Everything you want
  <small class="text-muted">And we try our best to make it available</small>
</h1>
<br/><br />

<% if current_user.carts.any? %>
  <% @carts.each do |cart| %>
    <div class="row">
      <div class="col-md-7 vertical-center">
        <img class="img-fluid rounded mb-3 mb-md-0" src= <%= cart.picture %> alt="Image unavailable">
      </div>
      <div class="col-md-5">
        <h3><%= cart.name %></h3>
        <p>Price: $ <%= cart.price %></p>
        <p>Category: <%= cart.category %></p>
        <p>Condition: <%= cart.condition %></p>
        <p>Description: <%= cart.description %></p>
      </div>
    </div>
    <hr>
  <% end %>
<% else %>
  <h1>
    You haven't add anything to your cart.
  </h1>
<% end %>

<br>

<div class="container">
  <div class="row">
    <div class="btn btn-primary btn-outline btn-block">
      <%= link_to "Remove all", {:controller => "carts", :action => "clear"} %>
    </div>
    <a></a>
    <div class="btn btn-primary btn-outline btn-block">
      <%= link_to "Check out all", {:controller => "transactions", :action => "updateTransaction"} %>
    </div>
  </div>
</div>

<%= render 'layouts/footer' %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cart.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @cart.price %>
</p>

<p>
  <strong>Category:</strong>
  <%= @cart.category %>
</p>

<p>
  <strong>Condition:</strong>
  <%= @cart.condition %>
</p>

<p>
  <strong>Description:</strong>
  <%= @cart.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @cart.user.email %>
</p>

<p>
  <strong>User:</strong>
  <%= @cart.user.id %>
</p>

<span>
  <%= image_tag @cart.picture if @cart.picture? %>
</span>

<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %>
<%= render 'layouts/footer' %>